version: '3.9'

services:
  postgres:
    image: ankane/pgvector
    container_name: ai_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ai_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-pgvector.sql:/docker-entrypoint-initdb.d/init-pgvector.sql
      - ./init-vector-store.sql:/docker-entrypoint-initdb.d/init-vector-store.sql


  ollama:
    image: ollama/ollama:latest
    container_name: ollama_service
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    entrypoint: >
      sh -c "
        ollama serve &
        until curl -s http://localhost:11434/api/tags >/dev/null; do
          echo 'Waiting for Ollama...'
          sleep 2
        done
        ollama pull llama3.1:8b
        ollama pull nomic-embed-text
        wait
      "
    restart: unless-stopped

  spring-app:
    build: .
    container_name: spring_ai_app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - ollama
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ai_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      OLLAMA_BASE_URL: http://ollama:11434

volumes:
  postgres_data:
  ollama_models: